# Generated by Django 5.2.4 on 2025-08-01 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_category_email_is_processed_email_processed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='items',
            field=models.TextField(blank=True, null=True),
        ),
    ]
