# Generated by Django 5.2.4 on 2025-08-04 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_transaction_items'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='items',
            new_name='item_description',
        ),
        migrations.AddField(
            model_name='transaction',
            name='item_brand',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='item_name',
            field=models.CharField(default='Unknown Item', max_length=255),
        ),
        migrations.AddField(
            model_name='transaction',
            name='item_quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='transaction',
            name='item_unit_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
