# Generated by Django 5.2.4 on 2025-08-06 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_email_last_sync_time_gmailtoken_last_sync_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financial_advice_summary', models.TextField()),
                ('abnormal_alert', models.TextField()),
                ('money_saving_tip', models.TextField()),
                ('report_date', models.DateTimeField(auto_now_add=True)),
                ('analysis_period', models.CharField(max_length=50)),
                ('total_transactions', models.IntegerField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_generated', models.BooleanField(default=False)),
                ('generation_status', models.CharField(default='pending', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_report',
                'ordering': ['-report_date'],
            },
        ),
    ]
