# Generated by Django 5.2.4 on 2025-08-07 19:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_aireport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aireport',
            name='period_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aireport',
            name='report_period_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aireport',
            name='report_period_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aireport',
            name='report_type',
            field=models.CharField(choices=[('general', '通用报告'), ('biweekly', '半个月报告'), ('monthly', '月度报告')], default='general', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='aireport',
            unique_together={('user', 'report_type', 'report_period_start', 'report_period_end')},
        ),
    ]
