# Generated by Django 5.2.4 on 2025-08-10 12:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_aireport_period_name_aireport_report_period_end_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='auto_share_rules',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_shared',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='shared_to_groups',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='GroupAIReport',
            fields=[
                ('group_ai_report_id', models.AutoField(primary_key=True, serialize=False)),
                ('group_id', models.IntegerField()),
                ('summary', models.TextField()),
                ('financial_advice', models.TextField()),
                ('spending_attribution', models.TextField()),
                ('anomaly_detection', models.TextField()),
                ('needs_vs_wants', models.TextField()),
                ('spending_patterns', models.TextField()),
                ('actionable_items', models.TextField()),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'group_ai_report',
                'ordering': ['-generated_at'],
                'unique_together': {('group_id', 'period_start', 'period_end')},
            },
        ),
        migrations.CreateModel(
            name='GroupTransaction',
            fields=[
                ('group_transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('group_id', models.IntegerField()),
                ('item_name', models.CharField(default='Unknown Item', max_length=255)),
                ('item_brand', models.CharField(blank=True, max_length=100, null=True)),
                ('item_quantity', models.IntegerField(default=1)),
                ('item_unit_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('item_description', models.TextField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('vendor', models.CharField(max_length=255)),
                ('transaction_date', models.DateTimeField()),
                ('source', models.CharField(default='shared', max_length=50)),
                ('note', models.TextField(blank=True, null=True)),
                ('is_manual', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_transactions', to='api.category')),
                ('original_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shared_transactions', to='api.transaction')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_transactions', to='api.subcategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'group_transaction',
                'ordering': ['-transaction_date'],
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.IntegerField()),
                ('group_name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('max_members', models.IntegerField(default=10)),
                ('role', models.CharField(choices=[('owner', '创建者'), ('member', '成员')], default='member', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'group',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'group_id')},
            },
        ),
    ]
