# Generated by Django 5.2.4 on 2025-08-10 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_transaction_auto_share_rules_transaction_is_shared_and_more'),
    ]

    operations = [
        # 删除现有的GroupAIReport表
        migrations.DeleteModel(
            name='GroupAIReport',
        ),
        # 重新创建GroupAIReport表，与个人AIReport保持一致
        migrations.CreateModel(
            name='GroupAIReport',
            fields=[
                ('group_ai_report_id', models.AutoField(primary_key=True, serialize=False)),
                ('group_id', models.IntegerField(help_text='组ID，不使用外键避免循环引用')),
                ('financial_advice_summary', models.TextField(help_text='理财建议总结（约50字）')),
                ('abnormal_alert', models.TextField(help_text='异常警报（约30字）')),
                ('money_saving_tip', models.TextField(help_text='省钱建议（约300字）')),
                ('report_date', models.DateTimeField(auto_now_add=True, help_text='报告生成时间')),
                ('analysis_period', models.CharField(help_text='分析周期（如"最近30天"）', max_length=50)),
                ('total_transactions', models.IntegerField(help_text='分析的交易总数')),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='总金额', max_digits=12)),
                ('is_generated', models.BooleanField(default=False, help_text='是否已生成')),
                ('generation_status', models.CharField(choices=[('pending', 'pending'), ('processing', 'processing'), ('completed', 'completed'), ('failed', 'failed')], default='pending', help_text='生成状态：pending, processing, completed, failed', max_length=20)),
                ('report_period_start', models.DateField(blank=True, help_text='报告周期开始日期', null=True)),
                ('report_period_end', models.DateField(blank=True, help_text='报告周期结束日期', null=True)),
                ('period_name', models.CharField(blank=True, help_text='周期名称（如"2024-01-01 to 2024-01-15"）', max_length=100, null=True)),
            ],
            options={
                'db_table': 'group_ai_report',
                'ordering': ['-report_date'],
            },
        ),
        # 添加唯一约束
        migrations.AlterUniqueTogether(
            name='groupaireport',
            unique_together={('group_id', 'report_period_start', 'report_period_end')},
        ),
    ]
