# Generated by Django 5.2.4 on 2025-08-04 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_items_transaction_item_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='last_sync_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gmailtoken',
            name='last_sync_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
